# Generated by Django 5.2.8 on 2026-07-14 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('communications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Circular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_no', models.CharField(max_length=60, unique=True)),
                ('title', models.CharField(max_length=220)),
                ('summary', models.TextField(blank=True)),
                ('audience', models.CharField(choices=[('ALL', 'All Employees'), ('MANAGEMENT', 'Management'), ('HR', 'HR & ESG'), ('FINANCE', 'Finance'), ('DEPARTMENT', 'Specific Department')], default='ALL', max_length=20)),
                ('effective_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('file_object_path', models.CharField(max_length=500)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_circulars', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circulars', to='accounts.department')),
            ],
            options={
                'ordering': ['-effective_date', '-created_at'],
            },
        ),
    ]
