# Generated by Django 5.2.8 on 2026-07-14 02:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('category', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('receipt_object_path', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('PENDING_HR', 'Pending HR Verification'), ('PENDING_FINANCE', 'Pending Finance Check'), ('PENDING_CEO', 'Pending CEO Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING_HR', max_length=30)),
                ('current_comment', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', 'status'], name='claims_clai_employe_f0d62f_idx'), models.Index(fields=['status', 'submitted_at'], name='claims_clai_status_38fbb1_idx')],
            },
        ),
    ]
